name: Run Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies for OpenCV
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0 libsm6 libxext6 libxrender-dev

      - name: Install Python Dependencies
        run: |
          pip install numpy pandas scikit-learn matplotlib opencv-python-headless

      - name: Run Test Script
        run: python distance_classification.py
